#!/usr/bin/env python3
"""Writes docs/rules/data_sources.md: for every data folder, how many entries were checked against the free 2024
Basic Rules (source.checked_against) and which ones were entered from knowledge and still need a book check."""
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FOLDERS = ["classes", "subclasses", "species", "backgrounds", "feats", "spells", "items", "magic_items", "monsters", "conditions"]


def main():
    lines = ["# Where the rules data comes from", "",
             "Generated by `python3 tools/data/data_sources.py`. **Checked** = every number compared with the free 2024",
             "Basic Rules on D&D Beyond (`source.checked_against: BR2024`). **From knowledge** = PHB/MM/CoS content the Basic",
             "Rules don't include, entered from knowledge of the books; these need a check against the owner's copy.", "",
             "| Data | Total | Checked | From knowledge |", "|---|---|---|---|"]
    unchecked = {}
    for folder in FOLDERS:
        entries = [json.loads(f.read_text()) for f in sorted((ROOT / "data" / folder).glob("*.json"))]
        checked = [e for e in entries if e.get("source", {}).get("checked_against")]
        rest = [e for e in entries if not e.get("source", {}).get("checked_against")]
        lines.append(f"| {folder} | {len(entries)} | {len(checked)} | {len(rest)} |")
        if rest:
            unchecked[folder] = rest
    lines += ["", "## Entries to check against the books", ""]
    for folder, rest in unchecked.items():
        by_book = defaultdict(list)
        for e in rest:
            by_book[e.get("source", {}).get("book", "?")].append(e.get("name", e["id"]))
        for book, names in by_book.items():
            lines.append(f"- **{folder}** ({book}, {len(names)}): " + ", ".join(sorted(names)))
    lines += ["", "## Magic items (DMG2024) entered from memory", "",
              "The 2024 Dungeon Master's Guide isn't in the free Basic Rules, so every magic item (data/magic_items, `book:",
              "DMG2024`) was entered from knowledge of the book (owner decision, personal use only): names, rarities,",
              "attunement, charges, DCs and effects all need a check against the owner's copy. The catalogue was rebuilt from",
              "memory as: every item of the 2014 DMG the 2024 book kept, the common items it folded in (from Xanathar's), the",
              "class implements (Amulet of the Devout, Arcane Grimoire, Bloodwell Vial, Moon Sickle, Rhythm-Maker's Drum,",
              "Dragonhide Belt, Wraps of Unarmed Power), Adamantine Weapon, and its artifacts. Left out as doubtful for the",
              "2024 book: the Sword of Answering, the All-Purpose Tool (Artificer only) and the Tasha's tattoos and shards.",
              "Artifacts' random properties use a condensed table (rules/equipment/magic_items.gd). The stat blocks for",
              "creatures the items summon (data/monsters, notes saying so) were entered from the 2025 Monster Manual the same way.",
              ""]
    (ROOT / "docs/rules/data_sources.md").write_text("\n".join(lines))
    print("\n".join(lines[6:6 + len(FOLDERS) + 1]))


if __name__ == "__main__":
    main()
