#!/usr/bin/env python3
"""Writes docs/rules/data_sources.md: for every data folder, how many entries were checked against the free 2024
Basic Rules (source.checked_against) and which ones were entered from knowledge and still need a book check."""
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FOLDERS = ["classes", "subclasses", "species", "backgrounds", "feats", "spells", "items", "magic_items", "monsters", "conditions"]


def main():
    lines = ["# Where the rules data comes from", "",
             "Generated by `python3 tools/data/data_sources.py`. **Checked** = every number compared with the free 2024",
             "Basic Rules on D&D Beyond (`source.checked_against: BR2024`). **From knowledge** = PHB/MM/CoS content the Basic",
             "Rules don't include, entered from knowledge of the books; these need a check against the owner's copy.",
             "**RtHW** (Ravenloft: The Horrors Within) entries were entered from the free 2025 Unearthed Arcana playtest",
             "(Horror Subclasses), published reviews of the book and Van Richten's Guide to Ravenloft, not from the book",
             "itself; every number needs a check against the owner's copy (each entry's `source.note` says what to check).", "",
             "| Data | Total | Checked | From knowledge |", "|---|---|---|---|"]
    unchecked = {}
    for folder in FOLDERS:
        entries = [json.loads(f.read_text()) for f in sorted((ROOT / "data" / folder).glob("*.json"))]
        checked = [e for e in entries if e.get("source", {}).get("checked_against")]
        rest = [e for e in entries if not e.get("source", {}).get("checked_against")]
        lines.append(f"| {folder} | {len(entries)} | {len(checked)} | {len(rest)} |")
        if rest:
            unchecked[folder] = rest
    lines += ["", "## Entries to check against the books", ""]
    for folder, rest in unchecked.items():
        by_book = defaultdict(list)
        for e in rest:
            by_book[e.get("source", {}).get("book", "?")].append(e.get("name", e["id"]))
        for book, names in by_book.items():
            lines.append(f"- **{folder}** ({book}, {len(names)}): " + ", ".join(sorted(names)))
    lines += ["", "## Magic items (DMG2024) entered from memory", "",
              "The 2024 Dungeon Master's Guide isn't in the free Basic Rules, so every magic item (data/magic_items, `book:",
              "DMG2024`) was entered from knowledge of the book (owner decision, personal use only): names, rarities,",
              "attunement, charges, DCs and effects all need a check against the owner's copy. The catalogue was rebuilt from",
              "memory as: every item of the 2014 DMG the 2024 book kept, the common items it folded in (from Xanathar's), the",
              "class implements (Amulet of the Devout, Arcane Grimoire, Bloodwell Vial, Moon Sickle, Rhythm-Maker's Drum,",
              "Dragonhide Belt, Wraps of Unarmed Power), Adamantine Weapon, and its artifacts. Left out as doubtful for the",
              "2024 book: the Sword of Answering, the All-Purpose Tool (Artificer only) and the Tasha's tattoos and shards.",
              "Artifacts' random properties use a condensed table (rules/equipment/magic_items.gd). The stat blocks for",
              "creatures the items summon (data/monsters, notes saying so) were entered from the 2025 Monster Manual the same way.",
              "Every item's `text`, `summary` and power text is written in our own words; only the game terms are the book's.",
              "", "## Death House (Curse of Strahd appendix B) from memory", "",
              "Death House's rooms, decor, encounters and treasure (data/locations/death_house_*.json,",
              "docs/regions/death_house_book_check.md) follow the book from memory, cross-checked against DM guides and play",
              "reports. Unsure, to check against the owner's copy:",
              "- Ground floor: the den's locked cabinet (heavy and light crossbow and 20 bolts; one memory adds a hand",
              "  crossbow and 20 bolts for each); whether the main hall's coat of arms and the cloakroom's black cloaks are the",
              "  book's; the kitchen oven's shape (domed, from a guide).",
              "- Second floor: the iron key in the library desk opening the attic padlock; the skeleton in leather armor with",
              "  three darts in the secret room; the three scrolls (bless, protection from poison, spiritual weapon).",
              "- Third floor and attic: that the attic stair has two secret doors (off the balcony, and behind the",
              "  nursemaid's mirror) and no DCs we know of (we use 12 and 10); that the secret stair to the dungeon starts in",
              "  the attic storage room's north-east corner; the nursemaid's specter in her suite and her remains in the",
              "  attic trunk; the master suite's portrait of Gustav and Elisabeth over the hearth.",
              "- Dungeon: the mimic as the door into the cult leaders' den (one guide puts it at the shrine's south door);",
              "  four ghouls in the passage; five shadows in the shrine set off by the orb or statue; the swarm of insects",
              "  in Elisabeth's crypt (23D); the spiked pit's DCs and damage (we keep 2d6 at DC 15); where the hidden",
              "  trapdoor (32) comes out (we use the village, open only after the sacrifice); the reliquary at the foot of the",
              "  lower stair; the alcove chests' contents (gems and trinkets become their gp value); the footlocker's",
              "  cloak of protection and spellbook (two sources agree).",
              "- Not modelled: a silvered shortsword (ours is plain), the mess kit, the yellow spellbook's spell list.",
              ""]
    (ROOT / "docs/rules/data_sources.md").write_text("\n".join(lines))
    start = lines.index("| Data | Total | Checked | From knowledge |")
    print("\n".join(lines[start:start + len(FOLDERS) + 2]))


if __name__ == "__main__":
    main()
