#!/usr/bin/env python3
"""Writes docs/rules/data_sources.md: for every data folder, how many entries were checked against the free 2024
Basic Rules (source.checked_against) and which ones were entered from knowledge and still need a book check."""
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FOLDERS = ["classes", "subclasses", "species", "backgrounds", "feats", "spells", "items", "monsters", "conditions"]


def main():
    lines = ["# Where the rules data comes from", "",
             "Generated by `python3 tools/data/data_sources.py`. **Checked** = every number compared with the free 2024",
             "Basic Rules on D&D Beyond (`source.checked_against: BR2024`). **From knowledge** = PHB/MM/CoS content the Basic",
             "Rules don't include, entered from knowledge of the books; these need a check against the owner's copy.", "",
             "| Data | Total | Checked | From knowledge |", "|---|---|---|---|"]
    unchecked = {}
    for folder in FOLDERS:
        entries = [json.loads(f.read_text()) for f in sorted((ROOT / "data" / folder).glob("*.json"))]
        checked = [e for e in entries if e.get("source", {}).get("checked_against")]
        rest = [e for e in entries if not e.get("source", {}).get("checked_against")]
        lines.append(f"| {folder} | {len(entries)} | {len(checked)} | {len(rest)} |")
        if rest:
            unchecked[folder] = rest
    lines += ["", "## Entries to check against the books", ""]
    for folder, rest in unchecked.items():
        by_book = defaultdict(list)
        for e in rest:
            by_book[e.get("source", {}).get("book", "?")].append(e.get("name", e["id"]))
        for book, names in by_book.items():
            lines.append(f"- **{folder}** ({book}, {len(names)}): " + ", ".join(sorted(names)))
    lines.append("")
    (ROOT / "docs/rules/data_sources.md").write_text("\n".join(lines))
    print("\n".join(lines[6:6 + len(FOLDERS) + 1]))


if __name__ == "__main__":
    main()
