#!/usr/bin/env python3
"""Lists every icon key the item data uses (docs/assets/item_icon_keys.md), for the icon art.

An item's icon is its `icon` field, else its own id. Magic items built on a base weapon or armor ("+1 Longsword",
id weapon_plus_1__longsword) use the template's `icon` if it has one, else the base item's `icon`, else the base item's
id: so every mundane weapon and armor id is a key too. Spell Scrolls use the template's `icon` (scroll).
"""
import glob
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "assets" / "item_icon_keys.md"


def load(folder):
    out = {}
    for f in sorted(glob.glob(str(ROOT / "data" / folder / "*.json"))):
        d = json.loads(Path(f).read_text())
        out[d["id"]] = d
    return out


def main():
    items = load("items")
    magic = load("magic_items")
    keys = {}

    def add(key, who):
        keys.setdefault(key, []).append(who)

    for iid, d in items.items():
        add(d.get("icon", iid), d["name"])
    templates = []
    for iid, d in magic.items():
        if "template" in d and d["template"].get("on") != "spell" and ("icon" not in d or d.get("icon_fallback")):
            templates.append(d["name"])
            continue
        add(d.get("icon", iid), d["name"])
    lines = ["# Item icon keys", "",
             "Generated by `python3 tools/data/item_icon_keys.py` from data/items and data/magic_items. Each key is an",
             "icon the game asks for (art/icons/items/<key>.png). An item without `icon` uses its own id.", "",
             "Items built on a base weapon or armor without an icon of their own use the base item's key (listed under",
             "the base item here): %s." % ", ".join(sorted(templates)), "",
             "| Key | Items |", "|---|---|"]
    for k in sorted(keys):
        names = sorted(set(keys[k]))
        shown = ", ".join(names[:6]) + (" and %d more" % (len(names) - 6) if len(names) > 6 else "")
        lines.append("| `%s` | %s |" % (k, shown))
    lines.append("")
    lines.append("%d keys." % len(keys))
    OUT.write_text("\n".join(lines) + "\n")
    print("%d icon keys -> %s" % (len(keys), OUT.relative_to(ROOT)))


if __name__ == "__main__":
    main()
