#!/usr/bin/env python3
"""Writes docs/voice/casting.md, the readable casting sheet, from audio/voice/casting.json (ADR 0012):
every voiced speaker, how much they say, the description their voice is designed from, and the voice cast."""
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import elevenlabs as el  # noqa: E402
import voice_lines  # noqa: E402

OUT = el.ROOT / "docs" / "voice" / "casting.md"


def main():
    c = el.casting()
    chars, count = Counter(), Counter()
    for e in voice_lines.lines().values():
        chars[e["speaker"]] += len(e["text"])
        count[e["speaker"]] += 1
    rows = ["# Casting sheet: who speaks, and how they sound", "",
            "Generated by `tools/audio/casting_sheet.py` from `audio/voice/casting.json` (ADR 0012). Each description is",
            "written from the speaker's voice bible in this folder and is what ElevenLabs designs the voice from: age,",
            "timbre, accent, rhythm and temperament. Lines and characters count each distinct voiced line once.", "",
            f"Model: `{c['model']}`, `{c['output_format']}`.", "",
            "| Speaker | Lines | Characters | Voice | Description |", "|---|---:|---:|---|---|"]
    for speaker, v in sorted(c["voices"].items(), key=lambda kv: -chars[kv[0]]):
        voice = v.get("name") or ("shares " + v["shares"] if v.get("shares") else "to cast")
        rows.append(f"| `{speaker}` | {count[speaker]:,} | {chars[speaker]:,} | {voice} | {v.get('description', '')} |")
    OUT.write_text("\n".join(rows) + "\n")
    print(f"Wrote {OUT.relative_to(el.ROOT)} ({len(c['voices'])} speakers)")


if __name__ == "__main__":
    main()
