#!/usr/bin/env python3
"""Writes docs/voice/casting.md, the readable casting sheet, from audio/voice/casting.json (ADR 0013):
every voiced speaker, how much they say, the description their voice is designed from, and the voice cast."""
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import elevenlabs as el  # noqa: E402
import voice_lines  # noqa: E402

OUT = el.ROOT / "docs" / "voice" / "casting.md"


def model_for(c, speaker):
    """The model the speaker's clips come from: their own, the one of the voice they share, else the pinned default
    (as generate_voice.model_for)."""
    v = c["voices"].get(speaker, {})
    return model_for(c, v["shares"]) if v.get("shares") else v.get("model", c["model"])


def main():
    c = el.casting()
    chars, count = Counter(), Counter()
    for e in voice_lines.lines().values():
        chars[e["speaker"]] += len(e["text"])
        count[e["speaker"]] += 1
    rows = ["# Casting sheet: who speaks, and how they sound", "",
            "Generated by `tools/audio/casting_sheet.py` from `audio/voice/casting.json` (ADR 0013). Each description is",
            "written from the speaker's voice bible in this folder and is what ElevenLabs designs the voice from: age,",
            "timbre, accent, rhythm and temperament. Lines and characters count each distinct voiced line once.", "",
            f"Model: `{c['model']}` unless the speaker names their own, `{c['output_format']}`. The Barovians, the Vistani and",
            "the castle's people speak on `eleven_v3`, which keeps the Eastern European accents that `eleven_v4` flattens",
            "(owner, 2026-10-07). New lines of every non-minor character are voiced on `eleven_v3` (owner, 2026-10-07);",
            "a speaker who moved keeps their older clips, and the Model column names the model those came from.",
            "`make voice SPEAKER=<id> RECAST=1` re-voices them; `tools/audio/generate_voice.py --models` counts them.", "",
            "| Speaker | Lines | Characters | Voice | Model | Description |", "|---|---:|---:|---|---|---|"]
    for speaker, v in sorted(c["voices"].items(), key=lambda kv: -chars[kv[0]]):
        voice = v.get("name") or ("shares " + v["shares"] if v.get("shares") else "to cast")
        model = f"`{model_for(c, speaker)}`" + (f" (older lines `{v['earlier_model']}`)" if v.get("earlier_model") else "")
        rows.append(f"| `{speaker}` | {count[speaker]:,} | {chars[speaker]:,} | {voice} | {model} | "
                    f"{v.get('description', '')} |")
    OUT.write_text("\n".join(rows) + "\n")
    print(f"Wrote {OUT.relative_to(el.ROOT)} ({len(c['voices'])} speakers)")


if __name__ == "__main__":
    main()
