extends TestCase

var _book_content: BookContentFixture

func before_each() -> void:
	_book_content = BookContentFixture.new()

func after_each() -> void:
	_book_content.restore()

func test_adept_spells_follow_maximum_slots_and_use_class_casting() -> void:
	var ch := TestChars.custom("wizard", "human", 4, {"ability_score_improvement": ["abjuration_adept"]})
	var shield := ch.granted_spells.filter(func(s: Dictionary) -> bool: return str(s["id"]) == "shield")
	assert_false(shield.is_empty())
	if shield.is_empty():return
	assert_eq(str(shield[0]["class_id"]), "wizard")
	assert_eq(str(shield[0]["ability"]), "int")
	assert_true(ch.granted_spells.any(func(s: Dictionary) -> bool: return str(s["id"]) == "lesser_restoration"))
	assert_false(ch.granted_spells.any(func(s: Dictionary) -> bool: return str(s["id"]) == "banishment"))
	while ch.slots_left(2) > 0:
		ch.expend_slot(2)
	ch.refresh()
	assert_true(ch.granted_spells.any(func(s: Dictionary) -> bool: return str(s["id"]) == "lesser_restoration"), "spent slots do not unprepare spells")

func test_adept_pact_slots_unlock_lower_level_spells() -> void:
	var ch := TestChars.custom("warlock", "human", 9, {"4.ability_score_improvement": ["abjuration_adept"]})
	for id: String in ["shield", "lesser_restoration", "protection_from_energy", "banishment", "mass_cure_wounds"]:
		assert_true(ch.granted_spells.any(func(s: Dictionary) -> bool: return str(s["id"]) == id), id)

func test_vestige_domain_choice_prepares_warlock_spells_at_warlock_levels() -> void:
	var ch := TestChars.custom("warlock", "human", 7, {"warlock_subclass": ["vestige_patron"], "vestige_spells": ["life"]})
	assert_true(ch.granted_spells.any(func(s: Dictionary) -> bool: return str(s["id"]) == "aura_of_life" and str(s["class_id"]) == "warlock" and str(s["ability"]) == "cha"))
	assert_false(ch.granted_spells.any(func(s: Dictionary) -> bool: return str(s["id"]) == "greater_restoration"))

func test_conditional_resistance_updates_immediately_when_crossing_bloodied() -> void:
	var c := TestChars.dummy(100)
	var feat := Compendium.shared().feat_data("boon_of_desperate_resilience")
	var fx := Effect.new("Boon", &"feat", "boon_of_desperate_resilience")
	for m: Variant in ((feat["benefits"] as Array)[-1] as Dictionary)["modifiers"]:
		fx.modifiers.append(Modifier.make(m as Dictionary, "Desperate Resilience"))
	c.add_effect(fx)
	assert_eq(c.take_damage(60, &"fire").final, 60, "damage is evaluated before crossing the threshold")
	assert_eq(c.take_damage(10, &"cold").final, 5)
	assert_eq(c.take_damage(10, &"force").final, 10)
	c.heal(100)
	assert_eq(c.resistance_source(&"cold"), "")

func test_bountiful_temp_hp_bonus_is_added_before_replacement_comparison() -> void:
	var c := TestChars.dummy(100)
	c.temp_hp = 10
	c.add_effect(Effect.new("Bountiful Health").with_modifier("temp_hp_bonus", {"value": 5}))
	assert_true(c.add_temp_hp(8))
	assert_eq(c.temp_hp, 13)
	assert_false(c.add_temp_hp(0), "a zero grant does not create Temporary HP")
	assert_eq(c.temp_hp, 13)

func test_fortifying_soul_selects_multiple_targets_and_expires() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 7, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var ally := TestCombat.hero(e, "ilse_varga", Vector2i(3, 3))
	TestCombat.punching_bag(e, Vector2i(10, 3))
	TestCombat.start_with(e, c)
	ch.hp = 1
	ally.creature.hp = 1
	var catalog := ActionCatalog.new(e)
	var action := catalog.find(c, "feat:recipe:fortifying_soul")
	assert_eq(str(action["targeting"]), "multi")
	assert_eq(int(action["count"]), maxi(1, ch.ability_mod(&"wis")))
	assert_false(catalog.perform(c, action, [c, c]).ok)
	assert_true(c.action_available)
	assert_eq(ch.resource_left("fortifying_soul"), 1)
	assert_true(catalog.perform(c, action, [c, ally]).ok)
	assert_true(ch.hp >= 9 and ally.creature.hp >= 9)
	assert_eq(ch.resource_left("fortifying_soul"), 0)
	assert_true(c.magic_action_used)
	assert_false((ally.creature.d20_sources(["save_vs:frightened"])["advantage"] as Array).is_empty())
	var fx := ally.creature.effects.filter(func(x: Effect) -> bool: return x.source_id == "fortifying_soul")[0] as Effect
	assert_eq(fx.source_kind, &"feature")
	assert_eq(fx.minutes_left, 60)
	ally.creature.advance_minutes(59)
	assert_false((ally.creature.d20_sources(["save_vs:frightened"])["advantage"] as Array).is_empty())
	ally.creature.advance_minutes(1)
	assert_true((ally.creature.d20_sources(["save_vs:frightened"])["advantage"] as Array).is_empty())

func test_arcane_infiltrator_dodge_uses_bonus_and_resource() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 3, {"versatile": ["arcane_infiltrator"]})
	# Use the real feature definition on an otherwise built character (origin pick keys vary by species).
	if not ch.features.any(func(f: Dictionary) -> bool: return str(f["id"]) == "arcane_infiltrator_benefit"):
		var f := ((Compendium.shared().feat_data("arcane_infiltrator")["benefits"] as Array)[-1] as Dictionary).duplicate(true)
		f["class_id"] = ""
		ch.features.append(f)
		ch.set_resource("arcane_infiltrator", "Arcane Infiltrator", ch.proficiency_bonus(), "long")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	TestCombat.punching_bag(e, Vector2i(10, 3))
	TestCombat.start_with(e, c)
	var catalog := ActionCatalog.new(e)
	var action := catalog.find(c, "feat:recipe:arcane_infiltrator_benefit")
	assert_true(catalog.perform(c, action).ok)
	assert_true(c.action_available)
	assert_false(c.bonus_available)
	assert_eq(ch.resource_left("arcane_infiltrator"), ch.proficiency_bonus() - 1)
	assert_true(ch.effects.any(func(f: Effect) -> bool: return f.name == "Dodging"))

func test_divine_foreknowledge_restores_only_with_eligible_slot() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("cleric", "human", 17, {"cleric_subclass": ["knowledge_domain"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	TestCombat.punching_bag(e, Vector2i(10, 3))
	TestCombat.start_with(e, c)
	assert_true(e.feature_recipes.perform(c, "divine_foreknowledge", []).ok)
	assert_false((ch.d20_sources(["check:all"])["advantage"] as Array).is_empty())
	var slots := ch.slots_left(5)
	assert_false(e.feature_recipes.perform(c, "divine_foreknowledge", [], 5).ok)
	assert_eq(ch.slots_left(5), slots)
	assert_true(e.feature_recipes.perform(c, "divine_foreknowledge", [], 6).ok)
	assert_eq(ch.resource_left("divine_foreknowledge"), 1)
	assert_false(c.bonus_available)

func test_winter_polar_strikes_is_per_target_per_turn_and_excludes_unarmed() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 11, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var a := TestCombat.punching_bag(e, Vector2i(3, 3))
	var b := TestCombat.punching_bag(e, Vector2i(3, 4))
	TestCombat.start_with(e, c)
	var p := WeaponProfile.new()
	p.item_id = "longsword"
	var option := {"kind": "weapon", "profile": p, "melee": true}
	var first := e.class_features.hit_dice(c, a, option, {})
	assert_true(first.any(func(d: Dictionary) -> bool: return str(d.get("label", "")) == "Polar Strikes" and str(d["dice"]) == "1d6"))
	assert_false(e.class_features.hit_dice(c, a, option, {}).any(func(d: Dictionary) -> bool: return str(d.get("label", "")) == "Polar Strikes"))
	assert_true(e.class_features.hit_dice(c, b, option, {}).any(func(d: Dictionary) -> bool: return str(d.get("label", "")) == "Polar Strikes"))
	e.end_turn()
	assert_true(e.class_features.hit_dice(c, a, option, {}).any(func(d: Dictionary) -> bool: return str(d.get("label", "")) == "Polar Strikes"), "it also works on another creature's turn")
	p.item_id = "unarmed_strike"
	assert_false(e.class_features.hit_dice(c, b, option, {}).any(func(d: Dictionary) -> bool: return str(d.get("label", "")) == "Polar Strikes"))

func test_winter_resistance_bypass_keeps_casting_class_provenance() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 5, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var a := TestCombat.punching_bag(e, Vector2i(3, 3), 500)
	a.creature.base_resistances.append("cold")
	TestCombat.start_with(e, c)
	assert_eq(e.deal_damage(c, a, [{"amount": 20, "type": "cold", "weapon": true, "item": "longsword"}], false, "Weapon").final, 20)
	assert_eq(e.deal_damage(c, a, [{"amount": 20, "type": "cold", "weapon": true, "item": "unarmed_strike"}], false, "Unarmed").final, 10)
	var ctx := {"c": c, "nums": {"class_id": "ranger"}}
	assert_eq(e.spells.deal_spell_damage(ctx, a, [{"amount": 20, "type": "cold"}], false, "Spell").final, 20)
	ctx["nums"] = {"class_id": "wizard"}
	assert_eq(e.spells.deal_spell_damage(ctx, a, [{"amount": 20, "type": "cold"}], false, "Multiclass spell").final, 10)
	a.creature.base_immunities.append("cold")
	ctx["nums"] = {"class_id": "ranger"}
	assert_eq(e.spells.deal_spell_damage(ctx, a, [{"amount": 20, "type": "cold"}], false, "Spell").final, 0)

func test_hunters_rime_free_cast_blocks_disengage_and_transfers_with_mark() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 5, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var a := TestCombat.punching_bag(e, Vector2i(3, 3), 500)
	var b := TestCombat.punching_bag(e, Vector2i(3, 4), 500)
	TestCombat.start_with(e, c)
	var r := e.spells.cast(c, "hunters_mark", 1, [a])
	assert_true(r.ok, r.reason)
	assert_true(ch.temp_hp >= 6 and ch.temp_hp <= 15)
	assert_false(e.can_disengage(a))
	assert_true(e.can_disengage(b))
	var hp := ch.temp_hp
	a.creature.hp = 0
	while true:
		e.end_turn()
		if e.current() == c:break
	var action := e.spells.sustained_for(c, "hunters_mark")
	assert_true(e.spells.use_sustained(c, str(action["id"]), [b]).ok)
	assert_true(e.can_disengage(a))
	assert_false(e.can_disengage(b))
	assert_eq(ch.temp_hp, hp, "moving the mark is not another casting")
	ch.concentration.end("test")
	assert_true(e.can_disengage(b))

func _give_feat(ch: Character, id: String) -> void:
	var feat := Compendium.shared().feat_data(id)
	for raw: Variant in feat["benefits"]:
		var f := (raw as Dictionary).duplicate(true)
		f["class_id"] = ""
		ch.features.append(f)
		if f.has("resource"):
			var res := f["resource"] as Dictionary
			ch.set_resource(str(res["id"]), str(res["name"]), Formula.evaluate(res["max"], ch.formula_context()), str(res["recharge"]))
		for md: Variant in f.get("modifiers", []):
			ch.add_effect(Effect.new(str(f["name"]), &"feat", str(f["id"])).with_modifier(str(md["stat"]), md as Dictionary))

func test_roll_responses_filter_magic_reaction_costs_and_targets() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 4)
	_give_feat(ch, "arcane_omens")
	var helper := e.add(ch, &"party", Vector2i(2, 3))
	var ally := TestCombat.hero(e, "ilse_varga", Vector2i(3, 3))
	var enemy := TestCombat.punching_bag(e, Vector2i(9, 3))
	TestCombat.start_with(e, helper)
	var check := D20Test.from_natural(D20Test.Kind.ABILITY_CHECK, 5, 0, 15)
	e.feature_recipes.after_d20(ally, check, ["check:wis"])
	assert_true(helper.reaction_available)
	var save := D20Test.from_natural(D20Test.Kind.SAVING_THROW, 14, 0, 15)
	e.feature_recipes.after_d20(ally, save, ["save:wis", "save:all"])
	assert_true(save.success)
	assert_false(helper.reaction_available)
	assert_eq(ch.resource_left("arcane_omens_benefit"), ch.proficiency_bonus() - 1)
	helper.reaction_available = true
	var hostile := D20Test.from_natural(D20Test.Kind.SAVING_THROW, 14, 0, 15)
	e.feature_recipes.after_d20(enemy, hostile, ["save:wis"])
	assert_false(hostile.success)
	assert_true(helper.reaction_available)

func test_spell_resistance_bonus_only_spends_on_failed_magical_save() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("fighter", "human", 4)
	_give_feat(ch, "spell_resistant")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	TestCombat.punching_bag(e, Vector2i(9, 3))
	TestCombat.start_with(e, c)
	var save := D20Test.from_natural(D20Test.Kind.SAVING_THROW, 14, 0, 15)
	e.feature_recipes.after_d20(c, save, ["save:con"])
	assert_false(save.success)
	assert_eq(ch.resource_left("spell_resistant_save"), ch.proficiency_bonus())
	e.feature_recipes.after_d20(c, save, ["save:con", "save_vs:spell"])
	assert_true(save.success)
	assert_true(c.reaction_available, "Magic Resistant does not cost a Reaction")
	assert_eq(ch.resource_left("spell_resistant_save"), ch.proficiency_bonus() - 1)

func test_fortunes_favor_recharges_at_owners_start_only() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 19)
	_give_feat(ch, "boon_of_fortunes_favor")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var t := TestCombat.punching_bag(e, Vector2i(9, 3))
	TestCombat.start_with(e, c)
	var save := D20Test.from_natural(D20Test.Kind.SAVING_THROW, 19, 0, 20)
	TestCombat.next_d20(e, 2)
	e.feature_recipes.after_d20(c, save, ["save:wis"])
	assert_eq(save.kept, 2, "must keep a worse result")
	assert_eq(ch.resource_left("boon_of_fortunes_favor_benefit"), 0)
	ch.on_turn_start(t.id)
	assert_eq(ch.resource_left("boon_of_fortunes_favor_benefit"), 0)
	ch.on_turn_start(c.id)
	assert_eq(ch.resource_left("boon_of_fortunes_favor_benefit"), 1)

func test_iron_mind_and_focused_conjuration_protect_only_the_stated_breaks() -> void:
	var ch := TestChars.custom("wizard", "human", 19)
	_give_feat(ch, "boon_of_the_iron_mind")
	var concentration := ch.begin_concentration("bless", "Bless")
	var hit := ch.take_damage(1, &"force", false, DiceRoller.new(1))
	assert_eq(hit.concentration_dc, 0)
	ch.add_condition(&"stunned", "test")
	assert_false(concentration.ended)
	ch.add_condition(&"petrified", "test")
	assert_true(concentration.ended)
	var conjurer := TestChars.custom("wizard", "human", 10, {"wizard_subclass": ["conjurer"]})
	conjurer.begin_concentration("summon_fey", "Summon Fey")
	assert_true(conjurer.concentration_damage_protected())
	conjurer.begin_concentration("bless", "Bless")
	assert_false(conjurer.concentration_damage_protected())

func test_benign_transposition_swap_range_upgrade_and_resource_restoration() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 6, {"wizard_subclass": ["conjurer"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var ally := TestCombat.hero(e, "ilse_varga", Vector2i(5, 3))
	var enemy := TestCombat.punching_bag(e, Vector2i(9, 3))
	TestCombat.start_with(e, c)
	var before := ch.resource_left("benign_transposition")
	assert_true(before >= 1)
	assert_false(e.feature_recipes.perform(c, "benign_transposition", [], 0, enemy.cell).ok)
	assert_eq(ch.resource_left("benign_transposition"), before)
	assert_true(c.bonus_available)
	assert_true(e.feature_recipes.perform(c, "benign_transposition", [], 0, ally.cell).ok)
	assert_eq(c.cell, Vector2i(5, 3))
	assert_eq(ally.cell, Vector2i(2, 3))
	assert_eq(ch.resource_left("benign_transposition"), before - 1)
	assert_false(c.bonus_available)
	var slots := ch.slots_left(3)
	assert_true(e.feature_recipes.perform(c, "benign_transposition", [], 3).ok)
	assert_eq(ch.slots_left(3), slots - 1)
	assert_eq(ch.resource_left("benign_transposition"), before)
	var action := ActionCatalog.new(e).find(c, "feat:recipe:benign_transposition")
	assert_eq(int(action["range"]), 60)

func test_durable_summons_requires_slot_and_tracks_its_temporary_hp() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 6, {"wizard_subclass": ["conjurer"]})
	(ch.spellcasting[0]["prepared"] as Array).append("summon_beast")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	TestCombat.punching_bag(e, Vector2i(10, 3))
	TestCombat.start_with(e, c)
	assert_true(e.spells.cast(c, "summon_beast", 2, [], Vector2(4.5, 3.5)).ok)
	var ids := e.spells.summoned[c.id] as Array
	var summon := e.get_c(str(ids.back()))
	assert_eq(summon.creature.temp_hp, 12)
	assert_eq(summon.creature.resistance_source(&"fire"), "Durable Summons")
	assert_eq(summon.creature.resistance_source(&"force"), "")
	summon.creature.add_temp_hp(20, "Replacement")
	assert_eq(summon.creature.resistance_source(&"fire"), "", "benefit is bound to these Temporary Hit Points")
	var free := TestChars.dummy(100)
	e.feature_recipes.after_summon({"c": c, "s": Compendium.shared().spell_data("summon_beast"), "slot": 2}, free)
	assert_eq(free.temp_hp, 0, "a slot level alone does not mean a slot was spent")

func test_splintered_summons_validates_two_spaces_and_shares_concentration() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 14, {"wizard_subclass": ["conjurer"]})
	(ch.spellcasting[0]["prepared"] as Array).append("summon_beast")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	TestCombat.punching_bag(e, Vector2i(10, 3))
	TestCombat.start_with(e, c)
	var action := ActionCatalog.new(e).find(c, "spell:summon_beast:splintered")
	assert_false(action.is_empty())
	assert_eq(str(action["targeting"]), "points")
	var before := ch.slots_left(2)
	assert_false(e.spells.cast(c, "summon_beast", 2, [], Vector2(4.5, 3.5), Vector2.ZERO,
		{"splintered": true, "choice": "land", "points": [Vector2(4.5, 3.5), Vector2(4.5, 3.5)]}).ok)
	assert_eq(ch.slots_left(2), before)
	assert_eq(ch.resource_left("splintered_summons"), 1)
	assert_true(c.action_available)
	assert_true(e.spells.cast(c, "summon_beast", 2, [], Vector2(4.5, 3.5), Vector2.ZERO,
		{"splintered": true, "choice": "land", "points": [Vector2(4.5, 3.5), Vector2(5.5, 4.5)]}).ok)
	var ids := e.spells.summoned[c.id] as Array
	assert_eq(ids.size(), 2)
	var ordinary := Monster.from_data(SummonBlocks.for_spell("summon_beast", 2, "land", {}))
	for id: Variant in ids:
		var spirit := e.get_c(str(id))
		assert_eq(spirit.creature.max_hp(), ordinary.max_hp() / 2)
		assert_eq(spirit.creature.hp, ordinary.max_hp() / 2)
		assert_eq(spirit.creature.temp_hp, 28)
		assert_true(spirit.is_player_controlled())
	assert_eq(ch.resource_left("splintered_summons"), 0)
	assert_true(e.feature_recipes.perform(c, "splintered_summons", [], 5).ok)
	assert_eq(ch.resource_left("splintered_summons"), 1)
	ch.concentration.end("test")
	for id: Variant in ids:
		assert_false(e.get_c(str(id)).is_alive())


func test_conjuration_adept_uses_selected_ability_only_for_matching_concentration() -> void:
	var ch := TestChars.custom("wizard", "human", 4, {"ability_score_improvement": ["conjuration_adept"], "conjuration_adept.abilities": ["wis"]})
	var mods := ch.modifiers_for(&"concentration_save_bonus")
	assert_eq(mods.size(), 1)
	assert_eq(mods[0].text("ability"), "wis")
	ch.begin_concentration("entangle", "Entangle")
	var plain := ch.save_bonus(&"con").total()
	var save := ch.roll_save(DiceRoller.new(42), &"con", 10, [], [], "Concentration", ["concentration"])
	assert_eq(save.breakdown.total(), plain + ch.ability_mod(&"wis"))
	var other := ch.roll_save(DiceRoller.new(42), &"con", 10)
	assert_eq(other.breakdown.total(), plain)
	ch.begin_concentration("slow", "Slow")
	other = ch.roll_save(DiceRoller.new(42), &"con", 10, [], [], "Concentration", ["concentration"])
	assert_eq(other.breakdown.total(), plain)

func test_transmutation_adept_requires_paid_slot_and_own_turn_then_expires() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 4, {"ability_score_improvement": ["transmutation_adept"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var foe := TestCombat.punching_bag(e, Vector2i(10, 3))
	TestCombat.start_with(e, c)
	var speed := ch.speed().total()
	assert_true(e.spells.cast(c, "jump", 2, [c]).ok)
	assert_eq(ch.speed().total(), speed + 10, "uses the actual slot level")
	e.end_turn()
	assert_eq(ch.speed().total(), speed)
	assert_eq(e.current(), foe)
	e.spells._after_cast_features({"c": c, "s": Compendium.shared().spell_data("jump"), "slot": 2}, false)
	assert_eq(ch.speed().total(), speed, "an off-turn spell does not trigger the bonus")
	e.end_turn()
	e.spells._after_cast_features({"c": c, "s": Compendium.shared().spell_data("jump"), "slot": 2}, true)
	assert_eq(ch.speed().total(), speed, "a free casting does not trigger the bonus")
	e.feature_recipes.after_cast(c, Compendium.shared().spell_data("mage_hand"), 0)
	assert_eq(ch.speed().total(), speed)


func test_chilling_retribution_prompts_on_hit_and_original_damage_still_lands() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 11, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var attacker := TestCombat.foe(e, "zombie", Vector2i(3, 3))
	attacker.creature.add_effect(Effect.new("Fail Wisdom").with_modifier("save", {"ability": "wis", "value": -100}))
	c.reaction_rules["chilling_retribution"] = "ask"
	TestCombat.start_with(e, attacker)
	var hp := ch.hp
	var uses := ch.resource_left("chilling_retribution")
	TestCombat.next_d20(e, 20)
	var hit := e.monster_attack(attacker, c, "slam")
	assert_true(hit.is_paused())
	assert_eq(e.pending.kind, "chilling_retribution")
	assert_eq(ch.hp, hp, "the response is before the hit damage")
	assert_true(e.answer_reaction(true).ok)
	assert_eq(ch.resource_left("chilling_retribution"), uses - 1)
	assert_false(c.reaction_available)
	assert_true(ch.hp < hp, "Stunning the attacker does not negate its triggering hit")
	assert_true(attacker.creature.has_condition(&"stunned"))
	assert_eq(attacker.speed(), 0)
	e.end_turn()
	assert_true(attacker.creature.has_condition(&"stunned"))
	e.end_turn()
	assert_false(attacker.creature.has_condition(&"stunned"))
	assert_true(attacker.speed() > 0)

func test_chilling_retribution_stun_immunity_and_decline_preserve_movement() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 11, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var attacker := TestCombat.punching_bag(e, Vector2i(11, 7), 100)
	attacker.creature.base_condition_immunities.append("stunned")
	attacker.creature.add_effect(Effect.new("Fail Wisdom").with_modifier("save", {"ability": "wis", "value": -100}))
	TestCombat.start_with(e, attacker)
	var uses := ch.resource_left("chilling_retribution")
	c.reaction_rules["chilling_retribution"] = "never"
	e.feature_recipes.synchronous_hit_responses(attacker, c)
	assert_eq(ch.resource_left("chilling_retribution"), uses)
	assert_true(c.reaction_available)
	c.reaction_rules["chilling_retribution"] = "auto"
	e.feature_recipes.synchronous_hit_responses(attacker, c)
	assert_eq(ch.resource_left("chilling_retribution"), uses - 1, "there is no range or sight limitation")
	assert_false(attacker.creature.has_condition(&"stunned"))
	assert_eq(attacker.speed(), 30, "the speed penalty depends on actually being Stunned")


func test_frozen_haunt_choice_pulse_resources_and_concentration_lifecycle() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 15, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var target := TestCombat.punching_bag(e, Vector2i(5, 3), 500)
	var ally := e.add(TestChars.dummy(500), &"party", Vector2i(3, 3))
	var far := TestCombat.punching_bag(e, Vector2i(11, 7), 500)
	target.creature.base_resistances.append("cold")
	c.reaction_rules["frozen_haunt_pulse"] = "ask"
	TestCombat.start_with(e, c)
	var catalog := ActionCatalog.new(e)
	var action := catalog.find(c, "spell:hunters_mark:frozen_haunt")
	assert_false(action.is_empty())
	assert_true(catalog.perform(c, action, [target]).ok)
	assert_true(ch.has_flag("frozen_haunt"))
	assert_eq(ch.resource_left("frozen_haunt"), 0)
	assert_eq(ch.take_damage(100, &"cold").final, 0)
	for condition: StringName in [&"grappled", &"prone", &"restrained"]:
		assert_false(ch.add_condition(condition, "test"))
	assert_true(e.pending != null)
	assert_false(e.pending.spends_reaction)
	assert_true(e.pending.target_choices.any(func(o: Dictionary) -> bool: return str(o["id"]) == ally.id))
	assert_false(e.pending.target_choices.any(func(o: Dictionary) -> bool: return str(o["id"]) == far.id))
	e.pending.selected_ids.assign([target.id, ally.id, far.id])
	assert_true(e.answer_reaction(true).ok)
	assert_true(c.reaction_available)
	assert_eq(target.creature.hp, ally.creature.hp, "Ranger feature Cold ignores Resistance")
	assert_true(target.creature.hp < 500)
	assert_eq(far.creature.hp, 500, "choices are revalidated when the prompt resolves")
	var slots := ch.slots_left(4)
	assert_true(e.feature_recipes.perform(c, "frozen_haunt", [], 4).ok)
	assert_eq(ch.slots_left(4), slots - 1)
	assert_eq(ch.resource_left("frozen_haunt"), 1)
	c.creature.concentration.end("test")
	assert_false(ch.has_flag("frozen_haunt"))
	assert_false(ch.is_condition_immune(&"grappled"))
	assert_eq(ch.take_damage(10, &"cold").final, 5, "normal Frost Resistance remains")

func test_frozen_haunt_pulses_at_turn_start_and_can_end_inside_creature() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 15, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var target := TestCombat.punching_bag(e, Vector2i(3, 3), 500)
	c.reaction_rules["frozen_haunt_pulse"] = "ask"
	TestCombat.start_with(e, c)
	assert_true(e.spells.cast(c, "hunters_mark", 1, [target], Vector2.INF, Vector2.ZERO, {"cast_form": "frozen_haunt"}).ok)
	assert_true(e.answer_reaction(false).ok)
	assert_eq(target.creature.hp, 500, "declining a pulse spares everyone")
	assert_true(e.move(c, target.cell).ok)
	assert_eq(c.speed() - c.movement_left, 10, "a creature's space is Difficult Terrain")
	ch.add_effect(Effect.new("Hold concentration").with_modifier("save", {"ability": "con", "value": 100}))
	var before := ch.hp + ch.temp_hp
	assert_true(e.end_turn().ok)
	assert_true(ch.hp + ch.temp_hp < before, "ending inside a creature deals Force damage")
	assert_true(ch.concentration != null)
	assert_true(e.end_turn().ok)
	assert_true(e.pending != null, "the next own turn starts with another selection")
	assert_eq(e.pending.kind, "frozen_haunt_pulse")
	assert_true(e.answer_reaction(false).ok)
	var old := c.cell
	ch.concentration.end("test")
	assert_false(e.triggered_features.embedded(c))
	assert_eq(e.grid.distance_ft(old, 1, c.cell, 1), 5, "shunt to a nearest empty space")

func test_frozen_haunt_wall_movement_and_rehooked_cleanup() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 15, {"ranger_subclass": ["winter_walker"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var target := TestCombat.punching_bag(e, Vector2i(5, 3), 500)
	c.reaction_rules["frozen_haunt_pulse"] = "never"
	TestCombat.start_with(e, c)
	assert_true(e.spells.cast(c, "hunters_mark", 1, [target], Vector2.INF, Vector2.ZERO, {"cast_form": "frozen_haunt"}).ok)
	e.grid.set_flag(Vector2i(3, 3), CombatGrid.WALL)
	assert_true(e.move(c, Vector2i(3, 3)).ok)
	assert_eq(c.speed() - c.movement_left, 10)
	for fx in ch.effects:
		if fx.source_id == "frozen_haunt":
			fx.on_end = Callable()
	e.spells.rehook_effects()
	ch.concentration.end("restored save ends the form")
	assert_false(e.triggered_features.embedded(c))
	assert_false(ch.has_flag("incorporeal_movement"))


func test_enchanting_conversationalist_adds_intelligence_only_to_chosen_skill() -> void:
	var ch := TestChars.custom("wizard", "human", 3, {"wizard_subclass": ["enchanter"], "enchanting_skill": ["persuasion"]})
	assert_eq(ch.skill_bonus(&"persuasion").total(), ch.ability_mod(&"cha") + ch.proficiency_bonus() + maxi(1, ch.ability_mod(&"int")))
	assert_eq(ch.skill_bonus(&"deception").total(), ch.ability_mod(&"cha"))

func test_hypnotic_presence_resource_sensory_gate_and_damage_end() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 3, {"wizard_subclass": ["enchanter"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var target := TestCombat.punching_bag(e, Vector2i(4, 3), 500)
	target.creature.add_effect(Effect.new("Fail Wisdom").with_modifier("save", {"ability": "wis", "value": -100}))
	TestCombat.start_with(e, c)
	target.creature.add_condition(&"blinded", "test")
	target.creature.add_condition(&"deafened", "test")
	var uses := ch.resource_left("hypnotic_presence")
	assert_false(e.feature_recipes.perform(c, "hypnotic_presence", [target]).ok)
	assert_eq(ch.resource_left("hypnotic_presence"), uses)
	assert_true(c.action_available)
	target.creature.remove_condition(&"deafened", "test")
	assert_true(e.feature_recipes.perform(c, "hypnotic_presence", [target]).ok, "hearing alone suffices")
	assert_eq(ch.resource_left("hypnotic_presence"), uses - 1)
	assert_true(target.creature.has_condition(&"charmed"))
	assert_true(target.creature.has_condition(&"incapacitated"))
	assert_eq(target.speed(), 0)
	assert_true(ch.concentration == null)
	e.deal_damage(c, target, [{"amount": 1, "type": "force"}], false, "test")
	assert_false(target.creature.has_condition(&"charmed"))
	assert_false(target.creature.has_condition(&"incapacitated"))
	assert_eq(target.speed(), 30)

func test_hypnotic_presence_ends_on_range_or_lost_senses_and_respects_charm_immunity() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 3, {"wizard_subclass": ["enchanter"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var target := TestCombat.punching_bag(e, Vector2i(4, 3), 500)
	target.creature.add_effect(Effect.new("Fail Wisdom").with_modifier("save", {"ability": "wis", "value": -100}))
	TestCombat.start_with(e, c)
	assert_true(e.feature_recipes.perform(c, "hypnotic_presence", [target]).ok)
	e.spells._teleport(c, Vector2i(1, 3), CombatResult.new())
	assert_false(target.creature.has_condition(&"charmed"), "moving either endpoint breaks the tether")
	e.spells._teleport(c, Vector2i(2, 3), CombatResult.new())
	c.action_available = true
	c.magic_action_used = false
	assert_true(e.feature_recipes.perform(c, "hypnotic_presence", [target]).ok)
	target.creature.add_condition(&"blinded", "test")
	e.spells.check_tethers()
	assert_true(target.creature.has_condition(&"charmed"), "it can still hear")
	target.creature.add_condition(&"deafened", "test")
	e.spells.check_tethers()
	assert_false(target.creature.has_condition(&"charmed"))
	target.creature.remove_condition(&"blinded", "test")
	target.creature.base_condition_immunities.append("charmed")
	ch.restore_resource("hypnotic_presence", 1)
	c.action_available = true
	c.magic_action_used = false
	assert_true(e.feature_recipes.perform(c, "hypnotic_presence", [target]).ok)
	assert_false(target.creature.has_condition(&"incapacitated"))
	assert_eq(target.speed(), 30)


func test_split_enchantment_spends_actual_slot_for_two_targets_and_validates_before_cost() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 6, {"wizard_subclass": ["enchanter"]})
	(ch.spellcasting[0]["prepared"] as Array).append("hold_person")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var a := TestCombat.punching_bag(e, Vector2i(4, 3), 500)
	var b := TestCombat.punching_bag(e, Vector2i(4, 4), 500)
	for target: Combatant in [a, b]:
		target.creature.add_effect(Effect.new("Fail Wisdom").with_modifier("save", {"ability": "wis", "value": -100}))
	TestCombat.start_with(e, c)
	var uses := ch.resource_left("split_enchantment")
	var slots := ch.slots_left(2)
	var higher := ch.slots_left(3)
	var catalog := ActionCatalog.new(e)
	var action := catalog.find(c, "spell:hold_person:split_enchantment")
	assert_false(action.is_empty())
	assert_false(catalog.perform(c, action, [a, a]).ok)
	assert_eq(ch.resource_left("split_enchantment"), uses)
	assert_eq(ch.slots_left(2), slots)
	assert_true(catalog.perform(c, action, [a, b]).ok)
	assert_eq(ch.resource_left("split_enchantment"), uses - 1)
	assert_eq(ch.slots_left(2), slots - 1)
	assert_eq(ch.slots_left(3), higher)
	assert_true(a.creature.has_condition(&"paralyzed"))
	assert_true(b.creature.has_condition(&"paralyzed"))
	assert_true(ch.concentration != null)

func test_empowered_transmutation_uses_effective_level_but_actual_slot_for_adept_speed() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 6, {"wizard_subclass": ["transmuter"], "ability_score_improvement": ["transmutation_adept"]})
	(ch.spellcasting[0]["prepared"] as Array).append("fly")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var ally := TestCombat.hero(e, "ilse_varga", Vector2i(3, 3))
	TestCombat.punching_bag(e, Vector2i(10, 3), 500)
	TestCombat.start_with(e, c)
	var speed := ch.speed().total()
	var uses := ch.resource_left("empowered_transmutation")
	assert_true(e.triggered_features.casting_boosts(c, Compendium.shared().spell_data("slow")).is_empty(), "a save spell is ineligible")
	assert_true(e.triggered_features.casting_boosts(c, Compendium.shared().spell_data("mage_hand")).is_empty(), "cantrips are ineligible")
	assert_false(e.spells.cast(c, "fly", 3, [c, ally], Vector2.INF, Vector2.ZERO, {"slot_boost": "empowered_transmutation", "free": true}).ok)
	assert_eq(ch.resource_left("empowered_transmutation"), uses)
	assert_true(e.spells.cast(c, "fly", 3, [c, ally], Vector2.INF, Vector2.ZERO, {"slot_boost": "empowered_transmutation"}).ok)
	assert_true(c.creature.speed("fly").total() >= 60)
	assert_true(ally.creature.speed("fly").total() >= 60, "effective level 4 grants a second target")
	assert_eq(ch.speed().total(), speed + 15, "Adept benefit uses the level 3 slot actually spent")
	assert_eq(ch.resource_left("empowered_transmutation"), uses - 1)


func test_bladesong_cost_bonuses_grip_and_free_dismissal() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 3, {"wizard_subclass": ["bladesinger"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	TestCombat.punching_bag(e, Vector2i(8, 3), 500)
	TestCombat.start_with(e, c)
	var ac := ch.ac_value()
	var speed := ch.speed().total()
	var uses := ch.resource_left("bladesong")
	assert_true(e.feature_recipes.perform(c, "bladesong", []).ok)
	assert_eq(ch.resource_left("bladesong"), uses - 1)
	assert_false(c.bonus_available)
	assert_true(c.action_available)
	assert_eq(ch.ac_value(), ac + maxi(1, ch.ability_mod(&"int")))
	assert_eq(ch.speed().total(), speed + 10)
	assert_false((ch.d20_sources(["check:acrobatics"])["advantage"] as Array).is_empty())
	var sword := WeaponProfile.build(ch, Compendium.shared().item_data("longsword"))
	assert_false(sword.two_hands, "a Versatile weapon defaults to one hand while singing")
	assert_eq(sword.ability, &"int")
	var unarmed := WeaponProfile.unarmed(ch)
	assert_eq(unarmed.ability, &"str", "Bladework does not affect Unarmed Strikes")
	ch.begin_concentration("detect_magic", "Detect Magic")
	var save := ch.roll_save(e.dice, &"con", 10, [], [], "Concentration", ["concentration"])
	assert_eq(save.breakdown.total(), ch.save_bonus(&"con").total() + ch.ability_mod(&"int"))
	assert_true(e.feature_recipes.perform(c, "bladesong:dismiss", []).ok)
	assert_eq(ch.ac_value(), ac)
	assert_eq(ch.speed().total(), speed)
	assert_true(ch.concentration != null, "ending Bladesong does not end spell Concentration")

func test_bladesong_armor_incapacitation_and_arcane_recovery() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 3, {"wizard_subclass": ["bladesinger"]})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	TestCombat.punching_bag(e, Vector2i(8, 3), 500)
	TestCombat.start_with(e, c)
	ch.inventory.append({"id": "leather_armor", "qty": 1, "slot": ""})
	assert_true(ch.equip("leather_armor", "armor"))
	var uses := ch.resource_left("bladesong")
	assert_false(e.feature_recipes.perform(c, "bladesong", []).ok)
	assert_true(c.bonus_available)
	assert_eq(ch.resource_left("bladesong"), uses)
	ch.unequip("armor")
	assert_true(e.feature_recipes.perform(c, "bladesong", []).ok)
	assert_true(ch.has_flag("bladesong"))
	assert_true(ch.equip("leather_armor", "armor"))
	assert_false(ch.has_flag("bladesong"))
	ch.unequip("armor")
	c.bonus_available = true
	assert_true(e.feature_recipes.perform(c, "bladesong", []).ok)
	ch.add_condition(&"stunned", "test")
	assert_false(ch.has_flag("bladesong"), "Stunned also incapacitates")
	var left := ch.resource_left("bladesong")
	assert_true(ch.spend_resource("arcane_recovery"))
	assert_eq(ch.resource_left("bladesong"), left + 1)
	assert_false(ch.spend_resource("arcane_recovery"))
	assert_eq(ch.resource_left("bladesong"), left + 1)

func test_two_handed_attack_ends_bladesong_even_on_a_miss() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 3, {"wizard_subclass": ["bladesinger"]})
	ch.inventory.append({"id": "greatsword", "qty": 1, "slot": ""})
	assert_true(ch.equip("greatsword", "main_hand"))
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var target := TestCombat.punching_bag(e, Vector2i(3, 3), 500)
	TestCombat.start_with(e, c)
	assert_true(e.feature_recipes.perform(c, "bladesong", []).ok)
	c.reaction_rules["heroic_inspiration"] = "never"
	TestCombat.next_d20(e, 1)
	assert_true(e.attack(c, target, "weapon:greatsword").ok)
	assert_false(ch.has_flag("bladesong"))


func test_bladesinger_cantrip_can_be_first_attack_but_only_once_per_action() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 6, {"wizard_subclass": ["bladesinger"]})
	(ch.spellcasting[0]["cantrips"] as Array).append("fire_bolt")
	ch.inventory.append({"id": "rapier", "qty": 1, "slot": ""})
	ch.equip("rapier", "main_hand")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	c.reaction_rules["heroic_inspiration"] = "never"
	var target := TestCombat.punching_bag(e, Vector2i(3, 3), 500)
	TestCombat.start_with(e, c)
	var catalog := ActionCatalog.new(e)
	var action := catalog.find(c, "war_magic:fire_bolt")
	assert_false(action.is_empty(), "can substitute the first attack")
	assert_true(catalog.perform(c, action, [target]).ok)
	assert_false(c.action_available)
	assert_eq(c.attacks_left, 1)
	assert_false(c.magic_action_used)
	assert_false(e.spells.cast(c, "fire_bolt", 0, [target], Vector2.INF, Vector2.ZERO, {"war_magic": true}).ok)
	assert_eq(c.attacks_left, 1)
	assert_true(e.attack(c, target, "weapon:rapier").ok)
	assert_eq(c.attacks_left, 0)
	e.end_turn()
	e.end_turn()
	assert_false(catalog.find(c, "war_magic:fire_bolt").is_empty())

func test_song_of_victory_offers_weapon_attacks_including_ranged_and_checks_before_cost() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 14, {"wizard_subclass": ["bladesinger"]})
	(ch.spellcasting[0]["cantrips"] as Array).append("fire_bolt")
	ch.inventory.append({"id": "shortbow", "qty": 1, "slot": ""})
	ch.inventory.append({"id": "arrow", "qty": 20, "slot": ""})
	ch.equip("shortbow", "main_hand")
	var c := e.add(ch, &"party", Vector2i(2, 3))
	c.reaction_rules["heroic_inspiration"] = "never"
	var target := TestCombat.punching_bag(e, Vector2i(8, 3), 500)
	TestCombat.start_with(e, c)
	assert_true(e.spells.cast(c, "fire_bolt", 0, [target]).ok)
	assert_eq(c.bonus_attack, "Song of Victory")
	var actions := e.feature_actions.list(c)
	assert_true(actions.any(func(a: Dictionary) -> bool: return str(a["id"]) == "feat:bonus_attack:song_of_victory:weapon:shortbow"))
	assert_false(actions.any(func(a: Dictionary) -> bool: return str(a["id"]).begins_with("feat:bonus_attack:song_of_victory:") and str(a["id"]).contains("unarmed")))
	assert_false(e.feature_actions.perform(c, "bonus_attack:song_of_victory:weapon:shortbow", null, Vector2.INF).ok)
	assert_true(c.bonus_available)
	var ammo := e.item_count(c, "arrow")
	assert_true(e.feature_actions.perform(c, "bonus_attack:song_of_victory:weapon:shortbow", target, Vector2.INF).ok)
	assert_eq(e.item_count(c, "arrow"), ammo - 1)
	assert_false(c.bonus_available)
	assert_eq(c.bonus_attack, "")


func test_cast_form_recipe_uses_its_own_resource_radius_damage_and_modifiers() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("ranger", "human", 3)
	ch.set_resource("ember_uses", "Ember Uses", 1, "long")
	ch.features.append({"id": "ember_form", "action": "passive", "summary": "", "name": "Ember Form", "class_id": "ranger", "cast_form": {
		"spell": "hunters_mark", "resource": "ember_uses", "modifiers": [{"stat": "immunity", "value": "acid"}],
		"pulse": {"radius": 5, "dice": "1d4", "type": "fire"}}})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	var near := TestCombat.punching_bag(e, Vector2i(3, 3), 500)
	var far := TestCombat.punching_bag(e, Vector2i(4, 3), 500)
	near.creature.base_immunities.append("cold")
	c.reaction_rules["ember_form_pulse"] = "ask"
	TestCombat.start_with(e, c)
	var catalog := ActionCatalog.new(e)
	assert_false(e.spells.cast(c, "hunters_mark", 1, [near], Vector2.INF, Vector2.ZERO, {"cast_form": "unknown"}).ok)
	assert_true(c.bonus_available)
	assert_eq(ch.resource_left("ember_uses"), 1)
	var action := catalog.find(c, "spell:hunters_mark:ember_form")
	assert_false(action.is_empty())
	assert_true(catalog.perform(c, action, [near]).ok)
	assert_eq(ch.resource_left("ember_uses"), 0)
	assert_eq(ch.take_damage(20, &"acid").final, 0)
	assert_false(ch.has_flag("incorporeal_movement"), "movement comes only from the recipe")
	assert_true(e.pending != null)
	if e.pending == null:return
	assert_eq(e.pending.kind, "ember_form_pulse")
	assert_false(e.pending.target_choices.any(func(t: Dictionary) -> bool: return str(t["id"]) == far.id))
	e.pending.selected_ids.assign([near.id, far.id])
	assert_true(e.answer_reaction(true).ok)
	assert_true(near.creature.hp >= 496 and near.creature.hp < 500, "recipe Fire damages a Cold-immune target")
	assert_eq(far.creature.hp, 500)
	e.triggered_features.turn_start(c)
	assert_true(e.pending != null)
	ch.concentration.end("form ended while selecting")
	var hp := near.creature.hp
	assert_true(e.answer_reaction(true).ok)
	assert_eq(near.creature.hp, hp, "an ended form cannot apply a delayed pulse")
	assert_eq(ch.take_damage(20, &"acid").final, 20)

func test_attack_recipes_use_class_filter_and_configured_weapon_restrictions() -> void:
	var e := TestCombat.open_field()
	var ch := TestChars.custom("wizard", "human", 3)
	(ch.spellcasting[0]["cantrips"] as Array).append("fire_bolt")
	ch.features.append({"id": "arcane_riposte", "action": "passive", "summary": "", "name": "Arcane Riposte", "after_cast_attack": {
		"casting_time": "action", "weapons_only": false, "allow_ranged": false}})
	ch.features.append({"id": "alternate_cantrip", "action": "passive", "summary": "", "name": "Alternate Cantrip", "attack_cantrip": {"class": "cleric"}})
	var c := e.add(ch, &"party", Vector2i(2, 3))
	c.reaction_rules["heroic_inspiration"] = "never"
	var target := TestCombat.punching_bag(e, Vector2i(8, 3), 500)
	TestCombat.start_with(e, c)
	var catalog := ActionCatalog.new(e)
	assert_true(catalog.find(c, "war_magic:fire_bolt").is_empty(), "the spell's casting class must match")
	(ch.features[-1]["attack_cantrip"] as Dictionary)["class"] = "wizard"
	var attack := catalog.find(c, "war_magic:fire_bolt")
	assert_false(attack.is_empty())
	assert_true(catalog.perform(c, attack, [target]).ok)
	assert_false(c.action_available)
	assert_eq(c.bonus_attack, "Arcane Riposte")
	var actions := e.feature_actions.list(c)
	assert_true(actions.any(func(a: Dictionary) -> bool: return str(a["id"]).begins_with("feat:bonus_attack:arcane_riposte:") and str(a["id"]).contains("unarmed")))
	c.bonus_attack = "Another benefit"
	assert_false(e.feature_actions.list(c).any(func(a: Dictionary) -> bool: return str(a["id"]).contains("arcane_riposte")), "a replaced attack does not inherit the previous trigger's label")

func test_resource_restore_recipe_requires_successful_positive_expenditure() -> void:
	var ch := TestChars.custom("wizard", "human", 1)
	ch.set_resource("trigger_pool", "Trigger Pool", 2, "long")
	ch.set_resource("restored_pool", "Restored Pool", 3, "long")
	assert_true(ch.spend_resource("restored_pool", 3))
	ch.add_effect(Effect.new("Linked Pools").with_modifier("resource_restore", {
		"when_spent": "trigger_pool", "resource": "restored_pool", "value": 2}))
	assert_true(ch.spend_resource("trigger_pool", 0))
	assert_eq(ch.resource_left("restored_pool"), 0)
	assert_false(ch.spend_resource("trigger_pool", 3))
	assert_eq(ch.resource_left("restored_pool"), 0)
	assert_true(ch.spend_resource("trigger_pool"))
	assert_eq(ch.resource_left("restored_pool"), 2)
	assert_true(ch.spend_resource("trigger_pool"))
	assert_eq(ch.resource_left("restored_pool"), 3, "restoration is capped at the pool maximum")
